name: mongodb-data-api

description: use any mongodb operation

global:
  databases:
    main: 
      driver: mongodb
      conn_string: |
        mongodb+srv://a|ap_var::MDB_USER|:a|ap_var::MDB_PASS|@a|ap_var::MDB_URL|

interfaces:
  # create
  mongodb/create:
    method: POST
    output: http

    actions:
      - name: CheckBody
        input: a|body
        assert:
          tests:
            - value: document
              is_not_null: true
              
      - name: MongoCreate
        run_when_succeeded:
          - previous
        database: main
        document_operation:
          database: 'data-api'
          collection: 'data'
          operation: insertOne
          insert: |
                a|CheckBody::document|

  mongodb/insert-many:
    method: POST
    output: http

    actions:
      - name: MongoInsertMany
        database: main
        document_operation:
          database: 'steam'
          collection: 'games'
          operation: insertMany
          insert: |
                a|body::docs|

  # read
  mongodb/read:
    method: POST
    output: http

    actions:
      - name: MongoRead
        database: main
        document_operation:
          database: 'data-api'
          collection: 'data'
          operation: findOne
          filter: a|body::document|

  # update
  mongodb/update:
    method: POST
    output: http

    actions:
      - name: MongoUpdate
        database: main
        document_operation:
          database: 'data-api'
          collection: 'data'
          operation: updateOne
          filter: '{"name": "a|body::name|"}'
          update: '{"$set": {"active": a|body::status|}}'
 
  # delete
  mongodb/delete:
    method: POST
    output: http

    actions:
      - name: MongoDelete
        database: main
        document_operation:
          database: 'data-api'
          collection: 'data'
          operation: deleteOne
          delete: | 
                a|body::document|


  # aggregate
  mongodb/aggregate:
    method: POST
    output: http

    actions:
      - name: MongoAggregate
        database: main
        document_operation:
          database: 'sample-analytics'
          collection: 'customers'
          operation: aggregate
          pipeline: |
            [ {
                "$match": {
                  "username": { "$regex": "^a|CheckBody::starts_with|", "$options": "i" }
                }
              },
              {
                "$project": {
                  "_id": 1,
                  "username": 1,
                  "email": 1
                }
              },
              {
               "$limit": 30
              }
            ]
